services:
  mysql:
    image: "mysql:8.0.43"
    container_name: "local-mysql"
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - mysql-data:/etc/data/mysql

volumes:
  mysql-data: